/* ===== ASK AI — AGENT LOOP =====
 *
 * Port of `agent/runAgent.ts` from the dashboard skill
 * (reference/chat-agent.md section 4). COPY VERBATIM — the only change is the
 * module wrapper: ForensIQ is a classic-script static site with no bundler, so
 * TypeScript types become JSDoc and the exports hang off the namespace. The
 * two-pass loop, the timeouts, the hardening notes and the user-facing
 * messages are unchanged.
 *
 * Two requests per question, one round, no re-planning:
 *   PASS 1 (route)  -> JSON naming which tools to call
 *   RUN TOOLS       -> in parallel, each isolates its own failure
 *   PASS 2 (answer) -> streamed markdown answer
 *
 * Do not edit this file when the dashboard changes — edit dashboardContext.js
 * and tools.js.
 *
 * Exposed as window.MunshotDashboard.agent.runAgent.
 */
'use strict';

(function () {
  var ns = (window.MunshotDashboard = window.MunshotDashboard || {});
  var agent = (ns.agent = ns.agent || {});

  var LLM_URL = 'https://fastapi.muns.io/query-router';

  // HARDENED: requests can no longer hang the panel on "Thinking…" forever.
  var ROUTER_TIMEOUT_MS = 45000;
  var STREAM_IDLE_TIMEOUT_MS = 60000;

  // HARDENED: users only ever see these plain-language messages; technical
  // detail goes to the console and to the host via sdk.sendError.
  var MSG_GENERIC = "Sorry, I couldn't answer that just now. Please try again.";
  var MSG_SESSION = 'Your Munshot session has expired. Please refresh the page and try again.';
  var MSG_BUSY = 'Ask AI is getting a lot of requests right now. Please wait a moment and try again.';
  var MSG_TIMEOUT = 'Ask AI is taking too long to respond. Please try again.';
  var MSG_EMPTY = "I couldn't get an answer this time. Please try asking again.";

  /** An error carrying a message that is safe to show to non-technical users. */
  function AgentError(userMessage, detail) {
    var err = new Error(detail);
    err.name = 'AgentError';
    err.userMessage = userMessage;
    err.isAgentError = true;
    return err;
  }

  function httpError(status, what) {
    var msg =
      status === 401 || status === 403 ? MSG_SESSION : status === 429 ? MSG_BUSY : MSG_GENERIC;
    return AgentError(msg, what + ' failed: HTTP ' + status);
  }

  function networkError(err, what) {
    var timedOut =
      err instanceof DOMException && (err.name === 'TimeoutError' || err.name === 'AbortError');
    return AgentError(
      timedOut ? MSG_TIMEOUT : MSG_GENERIC,
      what + ' failed: ' + String((err && err.message) || err)
    );
  }

  /**
   * HARDENED: the endpoint documents {"text": "..."}, but `text` can arrive as a
   * non-string (an already-parsed JSON object, an array of content blocks, a
   * number). Calling .trim() on it threw "e.trim is not a function". Normalise
   * every shape to a string before anything else touches it.
   */
  function toText(value) {
    if (typeof value === 'string') return value;
    if (value === null || value === undefined) return '';
    if (Array.isArray(value)) return value.map(toText).join('');
    if (typeof value === 'object') {
      if (typeof value.text === 'string') return value.text; // content block {type, text}
      try {
        return JSON.stringify(value); // e.g. an already-parsed {"tools":[...]} plan
      } catch (err) {
        return '';
      }
    }
    return String(value);
  }

  /**
   * @typedef {{ phase: 'thinking' }
   *   | { phase: 'fetching', sections: string[] }
   *   | { phase: 'streaming' }
   *   | { phase: 'done' }
   *   | { phase: 'error', message: string }} AgentPhase
   */

  /* ----------------------------- endpoint helpers ----------------------------- */

  async function callLlm(query, token, maxTokens) {
    var res;
    try {
      res = await fetch(LLM_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + token },
        body: JSON.stringify({
          query: query,
          llm_type: 'hosted_llm',
          stream: false,
          temperature: 0,
          max_tokens: maxTokens === undefined ? 500 : maxTokens,
        }),
        signal: AbortSignal.timeout(ROUTER_TIMEOUT_MS),
      });
    } catch (err) {
      throw networkError(err, 'LLM request');
    }
    if (!res.ok) throw httpError(res.status, 'LLM request');
    var json;
    try {
      json = await res.json();
    } catch (err) {
      throw AgentError(MSG_GENERIC, 'LLM request returned a non-JSON body');
    }
    if (json && json.text !== undefined && json.text !== null && typeof json.text !== 'string') {
      // HARDENED: make contract drift visible (DevTools console) instead of crashing.
      console.warn('[Ask AI] LLM endpoint returned non-string `text` of type', typeof json.text, json.text);
    }
    return toText(json && json.text);
  }

  /**
   * Streaming response is NDJSON — one JSON object per line, e.g. {"text":"..."}.
   * It is NOT server-sent events. Do not use EventSource.
   * Returns the number of characters streamed.
   */
  async function streamLlm(query, token, onChunk) {
    var ctrl = new AbortController();
    var idle = setTimeout(function () {
      ctrl.abort();
    }, STREAM_IDLE_TIMEOUT_MS);
    var resetIdle = function () {
      clearTimeout(idle);
      idle = setTimeout(function () {
        ctrl.abort();
      }, STREAM_IDLE_TIMEOUT_MS);
    };

    try {
      var res;
      try {
        res = await fetch(LLM_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + token },
          body: JSON.stringify({ query: query, llm_type: 'hosted_llm', stream: true }),
          signal: ctrl.signal,
        });
      } catch (err) {
        throw networkError(err, 'LLM stream');
      }
      if (!res.ok || !res.body) throw httpError(res.status, 'LLM stream');

      var reader = res.body.getReader();
      var decoder = new TextDecoder();
      var buffer = '';
      var streamed = 0;

      var flush = function (line) {
        var trimmed = line.trim();
        if (!trimmed) return;
        var obj;
        try {
          obj = JSON.parse(trimmed);
        } catch (err) {
          return; /* ignore malformed line */
        }
        // HARDENED: a server-side error line used to be thrown inside the same
        // try/catch that swallowed it, so the user silently got no answer.
        if (obj && obj.error) throw AgentError(MSG_GENERIC, 'LLM stream error: ' + toText(obj.error));
        // HARDENED: non-string chunks rendered as "[object Object]".
        var text = toText(obj && obj.text);
        if (text) {
          streamed += text.length;
          onChunk(text);
        }
      };

      for (;;) {
        var chunk;
        try {
          chunk = await reader.read();
        } catch (err) {
          throw networkError(err, 'LLM stream read');
        }
        if (chunk.done) break;
        resetIdle();
        buffer += decoder.decode(chunk.value, { stream: true });
        var lines = buffer.split('\n');
        buffer = lines.pop();
        if (buffer === undefined) buffer = '';
        lines.forEach(flush);
      }
      flush(buffer);
      return streamed;
    } finally {
      clearTimeout(idle);
    }
  }

  /* ------------------------------- tool planning ------------------------------ */

  /** @typedef {{ name: string, args: Record<string, any> }} PlannedCall */

  function parsePlan(raw) {
    var tools = agent.tools;
    var MAX_TOOLS_PER_TURN = agent.prompts.MAX_TOOLS_PER_TURN;
    var cleaned = toText(raw)
      .trim()
      .replace(/^```(?:json)?/i, '')
      .replace(/```$/, '')
      .trim();
    // HARDENED: also accept a JSON object wrapped in prose ("Here you go: {...}").
    var candidates = [cleaned];
    var start = cleaned.indexOf('{');
    var end = cleaned.lastIndexOf('}');
    if (start >= 0 && end > start && (start > 0 || end < cleaned.length - 1)) {
      candidates.push(cleaned.slice(start, end + 1));
    }
    for (var i = 0; i < candidates.length; i++) {
      try {
        var parsed = JSON.parse(candidates[i]);
        if (!parsed || !Array.isArray(parsed.tools)) continue;
        return parsed.tools
          .filter(function (c) {
            return (
              c &&
              typeof c.name === 'string' &&
              tools.some(function (t) {
                return t.name === c.name;
              })
            );
          })
          .slice(0, MAX_TOOLS_PER_TURN)
          .map(function (c) {
            return {
              name: c.name,
              args: c.args && typeof c.args === 'object' && !Array.isArray(c.args) ? c.args : {},
            };
          });
      } catch (err) {
        /* try the next candidate */
      }
    }
    return null;
  }

  /** Fill any arg declared `from: 'filter:<key>'` that the model left out. */
  function applyFilterDefaults(tool, args, filters) {
    var filled = Object.assign({}, args);
    Object.keys(tool.args).forEach(function (name) {
      var spec = tool.args[name];
      if (filled[name] !== undefined && filled[name] !== null && filled[name] !== '') return;
      if (spec.from && spec.from.indexOf('filter:') === 0) {
        var key = spec.from.slice('filter:'.length);
        if (filters[key]) filled[name] = filters[key];
      }
      if ((filled[name] === undefined || filled[name] === null) && spec.default) {
        filled[name] = spec.default;
      }
    });
    return filled;
  }

  /* --------------------------------- tool run -------------------------------- */

  function isRetryable(e) {
    return (e && e.name === 'TypeError') || (e && typeof e.status === 'number' && e.status >= 500);
  }

  async function runTool(call, filters, token) {
    var tools = agent.tools;
    var tool = tools.find(function (t) {
      return t.name === call.name;
    });
    var args = applyFilterDefaults(tool, call.args, filters);

    // One retry, network errors and 5xx only. Never retry a 4xx.
    for (var attempt = 0; attempt < 2; attempt++) {
      try {
        var data = await tool.run(args, token);
        return { name: tool.name, section: tool.section, ok: true, data: data };
      } catch (err) {
        if (attempt === 0 && isRetryable(err)) {
          await new Promise(function (r) {
            setTimeout(r, 500);
          });
          continue;
        }
        return {
          name: tool.name,
          section: tool.section,
          ok: false,
          error: toText(err && err.message) || 'request failed',
        };
      }
    }
    return { name: tool.name, section: tool.section, ok: false, error: 'request failed' };
  }

  /* ---------------------------------- agent ---------------------------------- */

  async function runAgent(opts) {
    var question = opts.question;
    var history = opts.history;
    var token = opts.token;
    var onPhase = opts.onPhase;
    var onChunk = opts.onChunk;

    var prompts = agent.prompts;
    var tools = agent.tools;

    try {
      // HARDENED: read filters inside the try so a failure here reaches the user.
      var filters = agent.dashboardContext.getFilters();

      // PASS 1 — route
      onPhase({ phase: 'thinking' });
      var routerPrompt = prompts.buildRouterPrompt(question, history, filters);

      var plan = parsePlan(await callLlm(routerPrompt, token));
      if (plan === null) {
        // one retry with a stricter nudge, then give up and answer with no data
        var strict = routerPrompt + '\n\nYour previous reply was not valid JSON. Reply with JSON only.';
        plan = parsePlan(await callLlm(strict, token));
        if (plan === null) plan = [];
      }

      // RUN TOOLS — in parallel, each isolates its own failure
      var results = [];
      if (plan.length) {
        var sections = [];
        plan.forEach(function (c) {
          var section = tools.find(function (t) {
            return t.name === c.name;
          }).section;
          if (sections.indexOf(section) < 0) sections.push(section);
        });
        onPhase({ phase: 'fetching', sections: sections });
        results = await Promise.all(
          plan.map(function (c) {
            return runTool(c, filters, token);
          })
        );
      }

      // PASS 2 — answer
      onPhase({ phase: 'streaming' });
      var answerPrompt = prompts.buildAnswerPrompt(question, history, results, filters);
      var streamed = await streamLlm(answerPrompt, token, onChunk);
      // HARDENED: an empty stream used to leave the question with no reply at all.
      if (streamed === 0) throw AgentError(MSG_EMPTY, 'LLM stream returned no text');

      onPhase({ phase: 'done' });
    } catch (err) {
      var detail = toText(err && err.message) || String(err);
      console.error('[Ask AI] request failed:', detail, err);
      ns.sdk.sendError('Ask AI request failed', 'ASK_AI_FAILED', {
        detail: detail,
        question: String(question).slice(0, 200),
      });
      onPhase({
        phase: 'error',
        message: err && err.isAgentError ? err.userMessage : MSG_GENERIC,
      });
    }
  }

  agent.runAgent = runAgent;
  agent.AgentError = AgentError;
})();
